#!/usr/bin/env ruby

$: << File.dirname(__FILE__)

require 'one_bursting_driver'


deploy_id = ARGV[0]
host      = ARGV[1]
id        = ARGV[2]

one_drv = ONEBurstingDriver.new(host)
puts one_drv.poll(deploy_id)