#!/usr/bin/env ruby

$: << File.dirname(__FILE__)

require 'one_bursting_driver'

deploy_id = ARGV[2]
file      = ARGV[0]
host      = ARGV[1]

one_drv = ONEBurstingDriver.new(host)

one_drv.restore(deploy_id)
