#!/usr/bin/env ruby

$: << File.dirname(__FILE__)

require 'one_bursting_driver'

deploy_id = ARGV[0]
file      = ARGV[1]
host      = ARGV[2]

one_drv = ONEBurstingDriver.new(host)

one_drv.save(deploy_id)